
FROM python:3.9-slim

WORKDIR /app
COPY task_filter.py /app/
COPY requirements.txt /app/

RUN mkdir -p /app/data
VOLUME /app/data

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5003

CMD ["python", "task_filter.py"]